version: '3'
services:
  java-app:
    image: felipeformentin/dockerlist-app
    ports:
    - "8080:8080"
    depends_on:
    - mysql
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
    - web
    environment:
    - SERVICE_PORTS=8080

  proxy:
    image: dockercloud/haproxy
    depends_on:
    - java-app
    environment:
    - BALANCE=roundrobin
    volumes:
    - haproxy
    ports:
    - 80:80
    networks:
    - web
    deploy:
      placement:
        constraints: [node.role == manager]

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: usbw
    volumes:
    - mysql:/var/lib/mysql
    ports:
    - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
    - 8082:8080
networks:
  webnet:
  web:
    driver: overlay
volumes:
  mysql:
  haproxy:
