version: '3'
services:
  java-app:
    image: felipeformentin/dockerlist-app
    ports:
    - "8080:8080"
    depends_on:
      - mysql

  angular-app:
    image: my-angular-app
    ports:
      - "4200:4200"

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: usbw
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
    - 8082:8080
networks:
  webnet:
volumes:
  mysql:
